global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'lapaylartop@gmail.com'
  smtp_auth_username: 'lapaylartop@gmail.com'
  smtp_auth_password: 'qmog kkhl oygd ecqo'
  smtp_require_tls: true

route:
  receiver: 'email-alerts'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'lapaylartop@gmail.com'